### ISSUE TITLE
Item wird trotz Alias nicht gefunden 

### ISSUE THREAD

**Issue by Olli** [heimrichhannot/contao-reader-bundle#1]
Hi,
ich habe ein das Lister und das Reader Bundle installiert. Die Auflistung erfolgt korrekt. Ein Detaillink wird aus dem Aliasfeld erzeugt.
Wenn ich da drauf klicke bekomme ich einen 404 .
Die Aliasabfrage habe ich mit der Autoitem Einstellung erledigt.
Der Contao-Debugmodus zeigt an, dass ein Query mit dem richtigen Alias auf das Aliasfeld der Tabelle ausgeführt wird und danach erfolgt noch mal ein Query auf den Datensatz anhand der ID. Gefunden wird der Datensatz also in der Datenbank.
Eigentlich müsste es klappen. 
Gibt es noch irgendwelche Dinge die beachtet werden müssen?

PS: Ich würde gern spezifischer fragen oder mehr Details zu dem Problem geben aber ich weiß nicht was noch benötigt wird. Ich halte die Konfiguration für mehr oder weniger einen No-Brainer

**Comment by Defcon0** [comment]
Eigentlich nicht, das hört sich schon relativ korrekt an. Zeigen die Detail-URLs der Liste denn korrekt auf die Zielseite, wo dann ein Modul vom Typ "Leser" (Reader-Bundle) liegt? Hast du XDebug? Dann könntest du dir mal einen Breakpoint in ModuleReader setzen und schauen, ob er da reingeht.

**Comment by Olli** [comment]
Nein ich habe kein Xdebug und kenne mich zugegebenermaßen mit dem Debugging in PHP nicht aus. Ich werde das mal ausprobieren - mal sehen wie weit ich komme.
Die Detail-URL ist auch korrekt "/reader/alias.html"
Ich habe mir die Contao Debugs angeschaut:
Es werden die Dateinfos der angehangen der dem Datensatz angehangenen Dateien abgerufen. Es wird "tl_reader_config_element" abgefragt. 
Danach kommt gleich "Router Symfony\Bundle\FrameworkBundle\Routing\Router was unable to generate route. Reason: 'Route 'contao_index' not found': Unable to generate a URL for the named route "contao_index" as such route does not exist." ... vielleicht hilft das erst mal so weit. Ich schau mir das mit dem Debugging mal an.

**Comment by Olli** [comment]
Xdebug wird nichts - ich habe php 7.3 und müsste auf 7.4 updaten. Das will ich jetzt nicht. 
Ich habe aber mal ein exit(); an die Stelle getan https://github.com/heimrichhannot/contao-reader-bundle/blob/a7528a5374c733585dbcdad521ddc51b90ee64fd/src/Module/ModuleReader.php#L106 und da wird dann auch nichts mehr ausgegeben. Somit geht er wohl ins Modul.

**Comment by koertho** [comment]
@Olli Kannst du mal einen Screenshot von der Fehlermeldung im Dev-Modus schicken?

**Comment by koertho** [comment]
@Olli Ach so, bitte auch immer Contao Version und Bundle Version angeben.

**Comment by Olli** [comment]
![Screenshot_2020-09-09 Symfony Profiler](https://user-images.githubusercontent.com/1754/92564260-68faaa00-f268-11ea-9d7a-33f307b99cce.png)

Contao 4.9.5
Bundle Version: 1.20.0

**Comment by koertho** [comment]
@Olli Danke, aber könntest du bitte einen Screenshot der kompletten Seite oder zumindest des komplette Stack-Trace schicken? Der Ausschnitt ist etwas zu kompakt :)

**Comment by Olli** [comment]
Das hatte ich falsch verstanden sorry - Bitte :)
https://imgur.com/a/B2YxQH4

**Comment by Defcon0** [comment]
Kannst du bitte mal die URL angeben, die du aufrufst (komplett inkl. Alias, also auto_item)? Dann bitte noch vom Record, der eigentlich gefunden werden soll, die ID und den Alias.

Kannst du dazu bitte noch folgendes versuchen:

1. Hast du einen Filter am Reader gesetzt? Falls ja, kannst du diesen bitte mal entfernen und es ohne probieren?
2. Kannst du bitte das Retrieval von auto_item auf ID stellen und versuchen, ob es dann geht?

Ich nehme an, es gibt irgendeine falsche Konfiguration bzw. abweichende DB-Werte, da es bei uns auch in 4.9.5 funktioniert.

**Comment by Olli** [comment]
Die URL ist http://contao-dev.local/arbeitsbuehne/test-anhaenger-1.html 
+----+------------------+
| id | alias            |
+----+------------------+
|  4 | test-anhaenger-1 |
+----+------------------+

1. Den Filter habe ich schon raus genommen - es hat sich keine Veränderung gezeigt.
2. ich weiß nicht wie ich das tun soll. Ich könnte  http://contao-dev.local/arbeitsbuehne/4.html  aufrufen. Da kommt das gleiche.

Ich fürchte, dass es eine falsche Konfiguration ist aber andererseits sieht es nicht wie Raketenwissenschaft aus und  ich meine das alles verstanden zu haben. Hier die Config
![grafik](https://user-images.githubusercontent.com/1754/92577531-41acd880-f27a-11ea-9e01-6faf378070f9.png)

**Comment by Defcon0** [comment]
Sehr mysteriös. Sieht alles ok aus :-( Wäre es eine Option für dich, dass wir mal per TeamViewer/AnyDesk schauen? So wird es schwierig, das zu debuggen.

**Comment by Olli** [comment]
Eigentlich wäre das OK aber ich wäre es nicht besser ich stell den SQL Dump und die composer.json zur Verfügung?

**Comment by Defcon0** [comment]
Das wäre auch ok ;-)

**Comment by Olli** [comment]
[contao-reader-bundle.tar.gz](https://github.com/heimrichhannot/contao-reader-bundle/files/5194092/contao-reader-bundle.tar.gz)

Anydesk geht auch für ein sneekpeek ins Contao bevor ihr euch die Arbeit macht das neu aufzusetzen.

**Comment by Defcon0** [comment]
Schicke uns die Nummer bitte mal an digitales@heimrich-hannot.de

**Comment by Olli** [comment]
Habt ihr es schon versucht?

**Comment by Olli** [comment]
Nachdem ich ewig rumgesucht habe und von Bugs in Atom behindert wurde habe ich nichts gefunden. Ich kann leider keine Breakpoints setzen ... zumindest werden die nicht an xdebug durchgereicht. Es ist ein Graus.

Ich habe aktuell 2 Erweiterungen installiert: heimrichhannot/contao-list-bundle & heimrichhannot/contao-reader-bundle
Mir ist nicht so ganz klar, wie ich weiter verfahren soll wenn es bei euch funktioniert. Ihr seid sicher, dass ihr nicht nur Softwaretests laufen lasst sondern das auch mal an einer echten Testinstallation probiert habt?

**Comment by Defcon0** [comment]
Ich ziehe mir mal fix deinen Stand drauf. Einen 404 ohne XDebug zu testen ist halt wirklich nicht praktikabel ;-)

**Comment by Olli** [comment]
MS Visualstudio hat es dann gebracht. 
catch (\UnusedArgumentsException $e) FrontendIndex generiert den 404 wegen getResponse aus FrontendTemplate.php  (denke ich)

**Comment by Olli** [comment]
Es handelt sich um "auto_item" den Input::getUnusedGet() zurück gibt.

**Comment by Defcon0** [comment]
Wir haben den Fehler gefunden und checken gleich ein neues Release ein.

**Comment by Defcon0** [comment]
OK, das neue Release ist live: 1.20.1

Kannst du es bitte mal testen? Bei uns hat es nun funktioniert.

**Comment by Olli** [comment]
:fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: 
Geht. Danke! :)

**Comment by Defcon0** [comment]
Top :-)
