### ISSUE TITLE
Minor errors in dev mode

### ISSUE THREAD

**Issue by a-v-l** [heimrichhannot/contao-reader-bundle#10]
**Context**
Contao version: 4.13.12
Bundle version: 1.39.3
PHP version: 8.1.11

**Description**
Several minor bugs in dev-mode:

1. Adding a new reader configuration leads to error: Warning: Undefined array key "pasteafter" in https://github.com/heimrichhannot/contao-reader-bundle/blob/ec1578239e104d9ef59f41ae74e62b813a864243/src/DataContainer/ReaderConfigContainer.php#L140 (& L141, L144, L148)
  `$GLOBALS['TL_LANG'][$table]` should be `$GLOBALS['TL_LANG']['DCA']`
2. Opening the details page leads to error: Warning: Undefined array key "onload_callback" in https://github.com/heimrichhannot/contao-reader-bundle/blob/ec1578239e104d9ef59f41ae74e62b813a864243/src/Manager/ReaderManager.php#L280
  `(\is_array($GLOBALS['TL_DCA'][$table]['config']['onload_callback']))` should be `(isset($GLOBALS['TL_DCA'][$table]['config']['onload_callback']) && \is_array($GLOBALS['TL_DCA'][$table]['config']['onload_callback']))`

All errors encountered in 'unclean' installation but reproduced in clean contao installation!

**Comment by vvohh** [comment]
your fix has been included in v1.39.4, thx for the contribution
