### ISSUE TITLE
How to access a database relation?

### ISSUE THREAD

**Issue by Olli** [heimrichhannot/contao-reader-bundle#13]
I've tried to access a database relation with {{ relationfield.anotherfield }} doesn't work so far.
Maybe I did miss something but how to access such fields from another database?
Greetings

**Comment by koertho** [comment]
How should that work? If you need Data from another database, you need to add it via event.

**Comment by Olli** [comment]
Not database but table ... so if I have a table which has through DCA a connection to another table how can I access the fields of that other table?

**Comment by koertho** [comment]
It is not possible / not integrated. In Contao this is done via model oder some DataTable magic. You can add the models or the related data from an event.

**Comment by Olli** [comment]
I'm so spoiled from Rails ... but thank you.

**Comment by Olli** [comment]
To get this clear ... you mean an onload event in the DCA config ... then fetch the relation and the specific field, put this onto a field in this DCA and than it becomes available in the TWIG template as a variable?

**Comment by koertho** [comment]
I mean this one for example: https://github.com/heimrichhannot/contao-reader-bundle/blob/master/src/Event/ReaderBeforeRenderEvent.php

**Comment by Olli** [comment]
Thanks. I'll try to try that :-)
