### ISSUE TITLE
Eigenes Template für die Ausgabe wird nicht gefunden

### ISSUE THREAD

**Issue by Olli** [heimrichhannot/contao-reader-bundle#2]
**Context**
Contao version: 4.9.5
Bundle version: 1.20.2
PHP version: 7.4

**Description**
Ich würde gern die Ausgabe selbst machen. Ich habe in /templates eine Datei mit dem Namen reader_item_test.html.twig angelegt mit dem selben Inhalt wie die Orginale des bundles.
Ich bekomme die Meldung "Unable to find template ... templates/reader_item_test.html.twig" obwohl die Datei da drin liegt.
Mach ich da was falsch oder ist das ein Bug? 
In der Auswahl (bei Instanz-Template) des Readers ist die Datei zumindest aufgeführt und ich konnte sie wählen.

**Comment by Defcon0** [comment]
Hi,

ja, den Fall hatten wir in der Vergangenheit nicht wirklich, weil wir immer Projekt-Bundles bauen, damit diese versioniert und per composer update-bar sind.

@koertho kümmert sich darum, da er an der baustelle ohnehin gerade dran war ;-)

**Comment by Olli** [comment]
Ein paar Infos: Twig versucht  im FilesystemLoader 235 den absoluten Pfad mit dem Templatenamen zu verketten. Der Templatename ist allerdings der schon der Absolute Pfad mit Templatenamen. 

hier https://github.com/heimrichhannot/contao-reader-bundle/blob/7c641aeb24f20622c70f6e0b1eb9d34a19033c21/src/Item/DefaultItem.php#L331

$this->_manager->getItemTemplateByName($event->getTemplate()) müsste "template_fu.html.twig" zurück geben aber gibt "/pfad/zum/contao/templates/template_fu.html.twig" zurück.

**Comment by Olli** [comment]
Das Thema trifft übrigens auch auf den Lister zu

**Comment by koertho** [comment]
@Olli Hi, ich habe gerade Version 1.21 veröffentlicht. Das war ziemlich viel anzupassen, wäre super, wenn du Feedback geben könntest.

**Comment by Olli** [comment]
Hi,
super! :)
Leider wird mir beim Aufruf der Readerconfiguration im BE folgendes for die Füße gekippt:

`

Uncaught Error: Argument 2 passed to HeimrichHannot\TwigSupportBundle\Filesystem\TwigTemplateLocator::getPrefixedFiles() must be of the type array, bool given, called in /my/dev/path/vendor/heimrichhannot/contao-twig-support-bundle/src/Filesystem/TwigTemplateLocator.php on line 133 

`

**Comment by koertho** [comment]
@Olli Danke für die schnelle Rückmeldung. Wenn du auf contao-twig-support-bundle 0.2.2 updatest, solltest du trockenen Fußes zur Readerconfiguration kommen ;)

**Comment by Olli** [comment]
Ok ich komme jetzt in die Reader Configuration. Ich kann außerdem mein Template spezifizieren und das Template wird auch genommen.
Damit sollte der Bug für das Modul behoben sein.
Nicht, dass es unter geht: Der Lister hat noch den selben Bug. 
Danke! :champagne: :heartbeat:

**Comment by koertho** [comment]
@Olli Am List-Bundle bin ich schon dran ;)

**Comment by koertho** [comment]
@Olli List bundle sollte jetzt auch klappen. Wenn doch ein Fehler auftritt, bitte dort ein Issue anlegen. Danke :)
