### ISSUE TITLE
Fehler bei Leserkonfigurationselement "Liste"

### ISSUE THREAD

**Issue by Olli** [heimrichhannot/contao-reader-bundle#4]
**Context**
Contao version: 4.9.9
Bundle version: 1.23.1
PHP version: 7.4

**Description**
Bei den Leserkonfigurationselementen gibt es einen Typ "Liste". Der produziert einen Fehler:
You have requested a non-existent service "huh.list.datacontainer.module".

**Comment by koertho** [comment]
@Olli Sollte in version 1.23.2 behoben sein.
